# Polish translation for sbackup
# Copyright (c) (c) 2006 Canonical Ltd, and Rosetta Contributors 2006
# This file is distributed under the same license as the sbackup package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2006.
#
msgid ""
msgstr ""
"Project-Id-Version: sbackup\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2013-01-10 22:47+0100\n"
"PO-Revision-Date: 2011-02-06 11:39+0000\n"
"Last-Translator: Jean-Peer Lorenz <Unknown>\n"
"Language-Team: Polish <pl@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2013-01-11 04:47+0000\n"
"X-Generator: Launchpad (build 16412)\n"

#: src/sbackup/backupproc.py:169 src/sbackup/pkginfo.py:85
#, python-format
msgid "SBackup Daemon <%(login)s@%(hostname)s>"
msgstr "Demon programu SBackup <%(login)s@%(hostname)s>"

#: src/sbackup/backupproc.py:173
#, python-format
msgid "[SBackup] [%(profile)s] Report of %(date)s"
msgstr ""

#: src/sbackup/backupproc.py:178 src/sbackup/core/profile_handler.py:282
msgid "No log file specified."
msgstr "Nie określono pliku dziennika."

#: src/sbackup/backupproc.py:183
msgid "Unable to find log file."
msgstr "Nie można odnaleźć pliku dziennika."

#: src/sbackup/backupproc.py:251
msgid ""
"Critical Error: No configuration file for the default profile was found!\n"
"\n"
"Now continue processing remaining profiles."
msgstr ""
"Błąd krytyczny: nie odnaleziono pliku ustawień dla domyślnego profilu!\n"
"\n"
"Przetwarzanie pozostałych profili będzie kontynuowane."

#: src/sbackup/backupproc.py:302
msgid "Backup was canceled by user."
msgstr "Tworzenie kopii zapasowej zostało anulowane przez użytkownika."

#: src/sbackup/backupproc.py:307
msgid "An error occurred during the cancellation of backup:"
msgstr "Wystąpił błąd podczas anulowania wykonywania kopii zapasowej:"

#: src/sbackup/backupproc.py:313
msgid "An error occurred during the backup:"
msgstr "Wystąpił błąd podczas wykonywania kopii zapasowej:"

#: src/sbackup/backupproc.py:330
msgid "Error when sending email:"
msgstr "Wystąpił błąd podczas wysyłania poczty elektronicznej:"

#: src/sbackup/backupproc.py:361
msgid "The following error(s) occurred before:"
msgstr "Poniższy błąd (błędy) wystąpił wcześniej:"

#: src/sbackup/backupproc.py:532
#, python-format
msgid ""
"Backup is not being started.\n"
"%s"
msgstr ""
"Wykonywanie kopii zapasowej nie zostało rozpoczęte.\n"
"%s"

#: src/sbackup/pkginfo.py:42
msgid ""
"This is a user friendly backup solution for common desktop needs. If you "
"want to help by submitting bugs, by translating or anything else please "
"visit our website."
msgstr ""
"Umożliwia w prosty sposób tworzenie kopii zapasowych. Informacje na temat "
"pomocy przy rozwoju programu dostępne są w witrynie internetowej."

#: src/sbackup/pkginfo.py:45
msgid "Maintainers:"
msgstr "Opiekunowie:"

#: src/sbackup/pkginfo.py:49
msgid "Former maintainers:"
msgstr "Byli opiekunowie:"

#: src/sbackup/pkginfo.py:53
msgid "Contributors:"
msgstr "Współtwórcy:"

#: src/sbackup/pkginfo.py:70
msgid "translator-credits"
msgstr ""
"Rafał Ryba <fafek2@gmail.com>\n"
"\n"
"Launchpad Contributions:\n"
"  Jarek Witkowski https://launchpad.net/~jarek-witkowski\n"
"  Jean-Peer Lorenz https://launchpad.net/~peer.loz\n"
"  Piotr Sokół https://launchpad.net/~psokol\n"
"  fafek2 https://launchpad.net/~fafek2"

#: src/sbackup/ar_backend/tar.py:109 src/sbackup/ar_backend/tar.py:167
#: src/sbackup/ar_backend/tar.py:213
msgid "Invalid archive type."
msgstr "Niepoprawny typ archiwum."

#: src/sbackup/ar_backend/tar.py:123
#, python-format
msgid "Effective path for `%s` is not available"
msgstr "Brak efektywnej ścieżki dla „%s”"

#: src/sbackup/ar_backend/tar.py:295
#, python-format
msgid "Unable to get effective path for `%s`"
msgstr "Nie można pozyskać efektywnej ścieżki dla „%s”"

#: src/sbackup/ar_backend/tar.py:344
msgid ""
"For the moment split functionality is not compatible with compress option."
msgstr "Na razie dzielenie skompresowanego archiwum nie jest możliwe."

#: src/sbackup/ar_backend/tar.py:353 src/sbackup/ar_backend/tar.py:414
#: src/sbackup/core/profile_handler.py:292
#, python-format
msgid "Unable to change permissions for file '%s'."
msgstr "Nie można zmienić uprawnień dla pliku '%s'."

#: src/sbackup/ar_backend/tar.py:362
#, python-format
msgid "Unable to remove temporary file `%(file)s`: %(error)s"
msgstr "Nie można usunąć pliku tymczasowego „%(file)s”: %(error)s"

#: src/sbackup/ar_backend/tar.py:378
msgid "Launching TAR to make incremental backup."
msgstr "Uruchamianie programu TAR w celu wykonania kopii przyrostowej."

#: src/sbackup/ar_backend/tar.py:407
msgid "Unable to find the SNAR file to make an incremental backup."
msgstr "Nie można odnaleźć pliku SNAR w celu wykonania kopii przyrostowej."

#: src/sbackup/ar_backend/tar.py:408
msgid "Falling back to full backup."
msgstr "Powracanie do kompletnej kopii zapasowej."

#: src/sbackup/ar_backend/tar.py:450
msgid "Launching TAR to make a full backup."
msgstr "Uruchamianie programu TAR w celu wykonania kompletnej kopii."

#: src/sbackup/ar_backend/tar.py:517
msgid "Leading '/' from member names were removed."
msgstr ""

#: src/sbackup/ar_backend/tar.py:519
msgid "Leading '/' from hard link targets were removed."
msgstr ""

#: src/sbackup/ar_backend/tar.py:528
#, python-format
msgid "TAR returned a message: %s"
msgstr "Program TAR zwrócił informację: %s"

#: src/sbackup/ar_backend/tar.py:530
#, python-format
msgid ""
"TAR returned messages:\n"
"%s"
msgstr ""
"Program TAR zwrócił informacje:\n"
"%s"

#: src/sbackup/ar_backend/tar.py:533
msgid "TAR has been finished successfully."
msgstr "Program TAR został poprawnie zakończony."

#: src/sbackup/ar_backend/tar.py:537
#, python-format
msgid "TAR returned a warning: %s"
msgstr ""
"Program TAR zwrócił ostrzeżenie:\n"
"%s"

#: src/sbackup/ar_backend/tar.py:539
#, python-format
msgid ""
"TAR returned warnings:\n"
"%s"
msgstr ""
"Program TAR zwrócił ostrzeżenia:\n"
"%s"

#: src/sbackup/ar_backend/tar.py:542
msgid "TAR returned warnings but has been finished successfully."
msgstr "Program TAR zwrócił ostrzeżenia ale został poprawnie zakończony."

#: src/sbackup/ar_backend/tar.py:546
msgid "Unable to finish successfully. TAR terminated with errors."
msgstr "Program TAR został zakończony z błędami."

#: src/sbackup/ar_backend/tar.py:727
#, python-format
msgid "Unable to terminate backend process: %s"
msgstr "Nie można zakończyć procesu modułu obsługi: %s"

#: src/sbackup/ar_backend/tar.py:760
msgid "Included"
msgstr "Dołączone"

#: src/sbackup/ar_backend/tar.py:760
msgid "Not changed"
msgstr "Niezmieniony"

#: src/sbackup/ar_backend/tar.py:760
msgid "Directory"
msgstr "Katalog"

#: src/sbackup/ar_backend/tar.py:788
msgid "Line must be a string"
msgstr "Wiersz musi być ciągiem"

#: src/sbackup/ar_backend/tar.py:804
msgid "Dumpdir inconsistancy : 'filename' is empty"
msgstr ""

#: src/sbackup/ar_backend/tar.py:817
msgid "Dumpdir inconsistancy : 'control' is empty"
msgstr ""

#: src/sbackup/ar_backend/tar.py:890
#, python-format
msgid "File '%s' does not exist."
msgstr "Plik „%s” nie istnieje."

#: src/sbackup/ar_backend/tar.py:1020 src/sbackup/ar_backend/tar.py:1054
#: src/sbackup/ar_backend/tar.py:1154
msgid "The snarfile header is incomplete."
msgstr "Nagłówek pliku snar jest niekompletny."

#: src/sbackup/ar_backend/tar.py:1323
msgid "A SnapshotFile is required"
msgstr ""

#: src/sbackup/ar_backend/tar.py:1423
#, python-format
msgid "Directory does not exist: %s."
msgstr "Katalog nie istnieje: %s"

#: src/sbackup/core/ConfigManager.py:330
#, python-format
msgid "Profile settings are being read from file '%s'."
msgstr "Odczytywanie profilu ustawień z pliku „%s”"

#: src/sbackup/core/ConfigManager.py:333
#, python-format
msgid ""
"Profile settings are being set to default values. Configuration file is set "
"to '%s'."
msgstr ""
"Przywrócono domyśle wartości ustawień profilu. Plik ustawień zapisano jako "
"„%s”."

#: src/sbackup/core/ConfigManager.py:479
msgid "Option 'target' is missing, aborting."
msgstr "Brakuje opcji 'cel', przerywam."

#: src/sbackup/core/ConfigManager.py:547
#, python-format
msgid ""
"Error while processing configuration:\n"
"\n"
"%(error)s in line `%(line)s`.\n"
"\n"
"Please check your configuration file."
msgstr ""

#: src/sbackup/core/ConfigManager.py:588 src/sbackup/core/ConfigManager.py:622
#, python-format
msgid ""
"Unable to evaluate '%(parameter)s' as a dictionary (value got = '%(value)r')."
msgstr ""

#: src/sbackup/core/ConfigManager.py:614
#, python-format
msgid ""
"Couldn't evaluate '%(parameter)s' as a dictionary (value got = '%(value)r' )"
msgstr ""

#: src/sbackup/core/ConfigManager.py:638
msgid "You must provide a dictionary."
msgstr ""

#: src/sbackup/core/ConfigManager.py:755
#, python-format
msgid "Log output for [%(profile)s] is directed to file '%(file)s'."
msgstr "Dziennik profilu „%(profile)s” jest zapisywany do pliku „%(file)s”."

#: src/sbackup/core/ConfigManager.py:762
#, python-format
msgid "Log output for [%s] is not directed into a file."
msgstr "Dziennik profilu „%s” nie jest zapisywany do pliku."

#: src/sbackup/core/ConfigManager.py:781
#, python-format
msgid "Unable to rename log file '%(src)s'->'%(dst)s': %(err)s"
msgstr ""
"Nie można zmienić nazwy pliku dziennika „%(src)s” na „%(dst)s”: %(err)s"

#: src/sbackup/core/ConfigManager.py:801
#, python-format
msgid "The config file '%s' couldn't be read!"
msgstr "Nie można wczytać pliku ustawień „%s”!"

#: src/sbackup/core/ConfigManager.py:813
#, python-format
msgid "section [%(section)s] in '%(configfile)s' should not exist, aborting"
msgstr ""
"sekcja [%(section)s] w '%(configfile)s' nie powinna istnieć, przerywam"

#: src/sbackup/core/ConfigManager.py:895
msgid "No schedule defined in configuration file. Probing from filesystem."
msgstr ""
"Brak harmonogramu kopii zapasowej w pliku ustawień. Przeszukiwanie ustawień "
"systemu."

#: src/sbackup/core/ConfigManager.py:988
#: src/sbackup/core/ConfigManager.py:1000
msgid "The config file is not set yet into this ConfigManager"
msgstr ""

#: src/sbackup/core/ConfigManager.py:1163
msgid "No receiver set."
msgstr "Nie określono odbiorcy."

#: src/sbackup/core/ConfigManager.py:1165
msgid "No SMTP server set."
msgstr "Nie określono serwera SMTP."

#: src/sbackup/core/ConfigManager.py:1168
msgid "Username set but no password specified."
msgstr "Nie określono hasła."

#: src/sbackup/core/ConfigManager.py:1171
msgid "Password set but no username specified."
msgstr "Nie określono nazwy użytkownika."

#: src/sbackup/core/ConfigManager.py:1174
msgid ""
"A certificate and key file is given while SSL option (smtptls=1) is not "
"set.\n"
"Select SSL in order to use Certificate and Key."
msgstr ""

#: src/sbackup/core/ConfigManager.py:1178
msgid ""
"When specifying a SSL certificate or key file, a key file resp. certificate "
"is mandatory."
msgstr ""

#: src/sbackup/core/ConfigManager.py:1373
msgid "Default Profile"
msgstr "Domyślny profil"

#: src/sbackup/core/ConfigManager.py:1374
msgid "Unknown Profile"
msgstr "Nieznany profil"

#: src/sbackup/core/ConfigManager.py:1428
msgid "Unlimited"
msgstr "Brak ograniczeń"

#: src/sbackup/core/ConfigManager.py:1429
msgid "100 MiB"
msgstr "100 MiB"

#: src/sbackup/core/ConfigManager.py:1430
msgid "250 MiB"
msgstr "250 MiB"

#: src/sbackup/core/ConfigManager.py:1431
msgid "650 MiB"
msgstr "650 MiB"

#: src/sbackup/core/ConfigManager.py:1432
msgid "2 GiB (FAT16)"
msgstr "2 GiB (FAT16)"

#: src/sbackup/core/ConfigManager.py:1433
msgid "4 GiB (FAT32)"
msgstr "4 GiB (FAT32)"

#: src/sbackup/core/ConfigManager.py:1434 src/sbackup/ui/configgui.py:279
#: src/sbackup/ui/configgui.py:1418
msgid "Custom"
msgstr "Własne"

#: src/sbackup/core/ConfigManager.py:1436
msgid "MP3 Music"
msgstr "Nagrania dźwięku w formacie MP3"

#: src/sbackup/core/ConfigManager.py:1437
msgid "AVI Video"
msgstr "Nagrania wideo w formacie AVI"

#: src/sbackup/core/ConfigManager.py:1438
#: src/sbackup/core/ConfigManager.py:1439
msgid "MPEG Video"
msgstr "Nagrania wideo w formacie MPEG"

#: src/sbackup/core/ConfigManager.py:1440
msgid "Matrjoshka Video"
msgstr "Nagrania wideo w formacie Matroska"

#: src/sbackup/core/ConfigManager.py:1441
msgid "OGG Multimedia container"
msgstr "Kontenery multimediów OGG"

#: src/sbackup/core/ConfigManager.py:1442
msgid "CD Images"
msgstr "Obrazy płyt CD"

#: src/sbackup/core/RestoreManager.py:80
#, python-format
msgid "File '%s' not found in the backup snapshot files list"
msgstr "Nie odnaleziono pliku „%s” na liście zrzutu danych kopii zapasowej."

#: src/sbackup/core/RestoreManager.py:82
#, python-format
msgid ""
"File '%(filename)s' not found in snapshot's [%(snapshotname)s] files list, "
"Skipped."
msgstr ""
"Nie odnaleziono pliku „%(filename)s” na liście zrzutu danych "
"„%(snapshotname)s”. Pominięto."

#: src/sbackup/core/SnapshotManager.py:114
#, python-format
msgid "Snapshot '%s' not found "
msgstr "Nie odnaleziono zrzutu danych „%s” "

#: src/sbackup/core/SnapshotManager.py:210
#, python-format
msgid "Invalid snapshot `%(name)s` found: Name of snapshot not valid."
msgstr "Wykryto niepoprawny zrzut danych „%(name)s”: niepoprawna nazwa."

#: src/sbackup/core/SnapshotManager.py:213
#, python-format
msgid "Invalid snapshot `%(name)s` found: %(error_cause)s."
msgstr "Odnaleziono niepoprawny zrzut danych „%(name)s”: %(error_cause)s."

#: src/sbackup/core/SnapshotManager.py:286
msgid "The snarfile header is incomplete !"
msgstr "Nagłówek pliku SNAR jest niekompletny!"

#: src/sbackup/core/SnapshotManager.py:429
#, python-format
msgid ""
"Snapshot '%s' is already Full, nothing to do (not changing it to full)."
msgstr "Zrzut danych „%s” jest już kompletny. Brak czynności do wykonania."

#: src/sbackup/core/profile_handler.py:101
#, python-format
msgid "Running of hooks: %s"
msgstr ""

#: src/sbackup/core/profile_handler.py:111
msgid "Preparation of backup process"
msgstr "Przygotowywanie do wykonania kopii zapasowej"

#: src/sbackup/core/profile_handler.py:146
#, python-format
msgid "Snapshot '%(name)s' is being made."
msgstr "Wykonywanie zrzutu danych „%(name)s”."

#: src/sbackup/core/profile_handler.py:154
#, python-format
msgid "Setting Base to '%(value)s'."
msgstr ""

#: src/sbackup/core/profile_handler.py:163
msgid "Setting packages File."
msgstr ""

#: src/sbackup/core/profile_handler.py:169
msgid "Problem when setting the packages list: "
msgstr ""

#: src/sbackup/core/profile_handler.py:173
msgid "Setting Excludes File."
msgstr "Określanie wykluczonych położeń"

#: src/sbackup/core/profile_handler.py:181
#, python-format
msgid "Setting compression format to `%s`"
msgstr "Ustawianie formatu kompresji na „%s”"

#: src/sbackup/core/profile_handler.py:188
#, python-format
msgid "Setting size of archive chunks to %s"
msgstr "Ustawianie rozmiaru fragmentów archiwum na %s"

#: src/sbackup/core/profile_handler.py:195
msgid "Option 'Follow symbolic links' is enabled."
msgstr "Opcja „Podążanie za dowiązaniami symbolicznymi” jest włączona."

#: src/sbackup/core/profile_handler.py:197
msgid "Option 'Follow symbolic links' is disabled."
msgstr "Opcja „Podążanie za dowiązaniami symbolicznymi” jest wyłączona."

#: src/sbackup/core/profile_handler.py:206
msgid "Snapshot is being committed"
msgstr ""

#: src/sbackup/core/profile_handler.py:220
#, python-format
msgid "Error while purging old snapshots: %s"
msgstr "Wystąpił błąd podczas usuwania przestarzałych zrzutów danych: %s"

#: src/sbackup/core/profile_handler.py:222
msgid "Backup process finished."
msgstr "Zakończono wykonywanie kopii zapasowej."

#: src/sbackup/core/profile_handler.py:229
msgid "Inspect file system and collect file infos"
msgstr "Analizowanie systemu plików i zbieranie informacji o plikach"

#: src/sbackup/core/profile_handler.py:240
msgid "Summary of backup"
msgstr "Podsumowanie kopii zapasowej"

#: src/sbackup/core/profile_handler.py:241
#, python-format
msgid "Number of directories: %s."
msgstr "Ilość katalogów: %s."

#: src/sbackup/core/profile_handler.py:242
#, python-format
msgid "Total number of files: %s."
msgstr "Ogólna ilość plików: %s."

#: src/sbackup/core/profile_handler.py:243
#, python-format
msgid "Number of symlinks: %s."
msgstr "Ilość dowiązań symbolicznych: %s."

#: src/sbackup/core/profile_handler.py:244
#, python-format
msgid "Number of files included in snapshot: %s."
msgstr "Ilość plików uwzględnionych w zrzucie danych: %s."

#: src/sbackup/core/profile_handler.py:245
#, python-format
msgid "Number of new files (also included): %s."
msgstr "Ilość uwzględnionych nowych plików: %s."

#: src/sbackup/core/profile_handler.py:246
#, python-format
msgid "Number of files skipped in incremental snapshot: %s."
msgstr ""
"Ilość plików pominiętych podczas wykonywania przyrostowego zrzutu danych: %s."

#: src/sbackup/core/profile_handler.py:247
#, python-format
msgid "Number of items forced to be excluded: %s."
msgstr "Ilość elementów wykluczonych przymusowo: %s."

#: src/sbackup/core/profile_handler.py:248
#, python-format
msgid "Number of items to be excluded by config: %s."
msgstr "Ilość elementów wykluczonych na podstawie ustawień: %s."

#: src/sbackup/core/profile_handler.py:249
#, python-format
msgid "Maximum free size required is '%s'."
msgstr "Maksymalna wymagana ilość wolnej przestrzeni wynosi %s."

#: src/sbackup/core/profile_handler.py:255
#, python-format
msgid "Available disk size is '%s'."
msgstr "Dostępna ilość przestrzeni dyskowej wynosi %s."

#: src/sbackup/core/profile_handler.py:257
#, python-format
msgid ""
"Not enough free space in the target directory for the planned backup (free: "
"%(freespace)s, required: %(neededspace)s)."
msgstr ""
"Brak wystarczającej ilości wolnej przestrzeni w położeniu docelowym dla "
"planowanej kopii zapasowej (wolna: %(freespace)s, wymagana %(neededspace)s)."

#: src/sbackup/core/profile_handler.py:277
msgid "Unable to copy log. File access is not initialized."
msgstr ""
"Nie można skopiować pliku dziennika. Dostęp do pliku nie został zainicjowany."

#: src/sbackup/core/profile_handler.py:295
#, python-format
msgid "Unable to copy log file: %s"
msgstr "Nie można skopiować pliku dziennika: %s"

#: src/sbackup/core/profile_handler.py:297
msgid "Unable to find logfile to copy into snapshot."
msgstr ""
"Nie można odnaleźć pliku dziennika w celu skopiowania go do zrzutu danych."

#: src/sbackup/core/profile_handler.py:299
msgid "No snapshot to copy logfile."
msgstr ""

#: src/sbackup/core/profile_handler.py:306
msgid "Processing of profile was canceled on user request\n"
msgstr "Przetwarzanie profilu zostało anulowane na życzenie użytkownika.\n"

#: src/sbackup/core/profile_handler.py:323
msgid "Processing of profile successfully finished (no errors)\n"
msgstr "Przetwarzanie profilu zostało zakończone pomyślnie.\n"

#: src/sbackup/core/profile_handler.py:329
#, python-format
msgid "Processing of profile failed with error: %s\n"
msgstr "Przetwarzanie profilu zostało zakończone z błędem: %s\n"

#: src/sbackup/core/profile_handler.py:340
#, python-format
msgid "Backup destination: %s"
msgstr "Położenie docelowe kopii zapasowej: %s"

#: src/sbackup/core/profile_handler.py:344
msgid "Unable to find destination directory."
msgstr "Nie można odnaleźć położenia docelowego."

#: src/sbackup/core/profile_handler.py:363
msgid "Unable to find destination directory even after retry."
msgstr "Nie można odnaleźć położenia docelowego po ponownej próbie."

#: src/sbackup/core/profile_handler.py:364
#: src/sbackup/core/profile_handler.py:371
#, python-format
msgid "Target directory '%(target)s' does not exist."
msgstr "Położenie docelowe „%(target)s” nie istnieje."

#: src/sbackup/core/profile_handler.py:377
#, python-format
msgid "Unable to access destination: %s"
msgstr "Nie można uzyskać dostępu do położenia docelowego: %s"

#: src/sbackup/core/snapshot.py:134
msgid "Snapshot is inconsistent: __name is not set "
msgstr ""

#: src/sbackup/core/snapshot.py:145
#, python-format
msgid "Name of snapshot '%s' doesn't match requirement"
msgstr "Nazwa zrzutu danych „%s” nie pasuje do wymaganej."

#: src/sbackup/core/snapshot.py:239
msgid "Snapshot is inconsistent: __snapshotpath is not set "
msgstr ""

#: src/sbackup/core/snapshot.py:318
#, python-format
msgid ""
"The snapshot compression format is supposed to be '%s' but the corresponding "
"well named file wasn't found"
msgstr ""

#: src/sbackup/core/snapshot.py:342
#, python-format
msgid ""
"%(file)s doesn't contain valid value. Ignoring incomplete or non - backup "
"directory. "
msgstr ""

#: src/sbackup/core/snapshot.py:478
#, python-format
msgid "Name of Snapshot not valid : %s"
msgstr "Niepoprawna nazwa zrzutu danych: %s"

#: src/sbackup/core/snapshot.py:496
#, python-format
msgid "Name of base not valid : %s"
msgstr "Niepoprawna nazwa bazy: %s"

#: src/sbackup/core/snapshot.py:542
#, python-format
msgid "Invalid name of snapshot: %s"
msgstr "Niepoprawna nazwa zrzutu danych: %s"

#: src/sbackup/core/snapshot.py:546
msgid "Unable to read mandatory file `ver`"
msgstr ""

#: src/sbackup/core/snapshot.py:591
msgid "Base name must be set for incremental backup."
msgstr "Należy określić nazwę bazy dla przyrostowej kopii zapasowej."

#: src/sbackup/fs_backend/_fuse_fam.py:106
msgid "Initializing FUSE File Access Manager."
msgstr "Inicjowanie menedżera dostępu FUSE"

#: src/sbackup/fs_backend/_fuse_fam.py:129
msgid "Terminating FUSE File Access Manager."
msgstr "Kończenie działania menedżera dostępu plików FUSE"

#: src/sbackup/fs_backend/_fuse_utils.py:45
#: src/sbackup/fs_backend/_gio_utils.py:109
msgid "SFTP"
msgstr "SFTP"

#: src/sbackup/fs_backend/_fuse_utils.py:46
#: src/sbackup/fs_backend/_gio_utils.py:110
msgid "SSH"
msgstr "SSH"

#: src/sbackup/fs_backend/_fuse_utils.py:47
#: src/sbackup/fs_backend/_gio_utils.py:111
msgid "FTP"
msgstr "FTP"

#: src/sbackup/fs_backend/_gio_fam.py:100
msgid "Initializing GIO File Access Manager."
msgstr "Inicjowanie menedżera dostępu GIO"

#: src/sbackup/fs_backend/_gio_fam.py:114
msgid "Terminating GIO File Access Manager."
msgstr "Kończenie działania menedżera dostępu GIO"

#: src/sbackup/fs_backend/_gio_utils.py:95
msgid "Unknown error code:"
msgstr ""

#: src/sbackup/fs_backend/_gio_utils.py:112
msgid "NFS"
msgstr "NFS"

#: src/sbackup/fs_backend/_gio_utils.py:113
msgid "SMB"
msgstr "SMB"

#: src/sbackup/fs_backend/_gio_utils.py:193
msgid "Unable to get mount: path is not mounted"
msgstr ""

#: src/sbackup/fs_backend/_gio_utils.py:195
msgid "Unable to get mount: path not found when mounting (is probably local)"
msgstr ""

#: src/sbackup/fs_backend/_gio_utils.py:197
#: src/sbackup/fs_backend/_gio_utils.py:200
#, python-format
msgid "Unable to get mount: %s"
msgstr ""

#: src/sbackup/fs_backend/_gio_utils.py:250
msgid "Unable to un-set mount flag: path is not stored"
msgstr ""

#: src/sbackup/fs_backend/_gio_utils.py:352
msgid "Path is already mounted."
msgstr "Położenie jest już zamontowane."

#: src/sbackup/fs_backend/_gio_utils.py:380
msgid "Path is not mounted."
msgstr "Położenie nie jest zamontowane."

#: src/sbackup/fs_backend/_gio_utils.py:887
msgid "test specified path for existence using GIO"
msgstr ""

#: src/sbackup/fs_backend/_gio_utils.py:900
msgid "Create testdir"
msgstr ""

#: src/sbackup/fs_backend/_gio_utils.py:905
msgid "Test testfile for existence"
msgstr ""

#: src/sbackup/fs_backend/_gio_utils.py:912
msgid "Create file"
msgstr "Utwórz plik"

#: src/sbackup/fs_backend/_gio_utils.py:919
msgid "Re-read test file"
msgstr ""

#: src/sbackup/fs_backend/_gio_utils.py:931
msgid "Remove file"
msgstr "Usuń plik"

#: src/sbackup/fs_backend/_gio_utils.py:933
msgid "Remove dir"
msgstr "Usuń katalog"

#: src/sbackup/fuse_plugins/__init__.py:160
#, python-format
msgid "Unable to import plugin `%(plugin_name)s`: %(error_cause)s "
msgstr "Nie można zaimportować wtyczki „%(plugin_name)s”: %(error_cause)s. "

#: src/sbackup/fuse_plugins/ftpFuseFAM.py:117
#, python-format
msgid ""
"Couldn't found external application 'curlftpfs' needed for handling of ftp "
"sites: %s"
msgstr ""
"Nie odnaleziono programu „curlftpfs” potrzebnego do obsługi położeń ftp: %s."

#: src/sbackup/fuse_plugins/ftpFuseFAM.py:127
#: src/sbackup/fuse_plugins/sftpFuseFAM.py:124
#, python-format
msgid "Couldn't mount '%(server)s' into '%(mountpoint)s' : %(error)s"
msgstr ""
"Nie udało się zamontować „%(server)s” w katalogu „%(mountpoint)s”: %(error)s."

#: src/sbackup/fuse_plugins/ftpFuseFAM.py:141
msgid "FTP schema is: ftp://user:pass@server/anything"
msgstr ""
"Wzór adresu FTP: ftp://nazwa\\_użytkownika:hasło@nazwa\\_komputera/zdalne\\"
"_położenie"

#: src/sbackup/fuse_plugins/ftpFuseFAM.py:188
#, python-format
msgid ""
"Error matching the schema 'ftp://user:pass@server/anything' with '%s' (The "
"'/' after server is mandatory)"
msgstr ""
"Wystąpił błąd podczas dopasowywania ciągu „%s” do wzoru „ftp://nazwa\\"
"_użytkownika:hasło@nazwa\\_serwera/zdalne\\_położenie” (znak „/” jest "
"wymagany po nazwie serwera)."

#: src/sbackup/fuse_plugins/sftpFuseFAM.py:114
#, python-format
msgid ""
"Couldn't found external application 'curlftpfs' needed for handling of sftp "
"sites: %s"
msgstr ""
"Nie odnaleziono programu „curlftpfs” potrzebnego do obsługi położeń sftp: %s."

#: src/sbackup/fuse_plugins/sftpFuseFAM.py:138
msgid "SFTP schema is like : sftp://user:pass@server/anything"
msgstr ""
"Wzór adresu SFTP: sftp://nazwa\\_użytkownika:hasło@nazwa\\_komputera/zdalne\\"
"_położenie"

#: src/sbackup/fuse_plugins/sftpFuseFAM.py:185
#, python-format
msgid ""
"Error matching the schema 'sftp://user:pass@server/anything' with '%s' (The "
"'/' after server is mandatory)"
msgstr ""
"Wystąpił błąd podczas dopasowywania ciągu „%s” do wzoru „sftp://nazwa\\"
"_użytkownika:hasło@nazwa\\_serwera/zdalne\\_położenie” (znak „/” jest "
"wymagany po nazwie serwera)."

#: src/sbackup/fuse_plugins/sshFuseFAM.py:81
#, python-format
msgid ""
"Error matching the schema 'ssh://user:pass@example.com/home/' with '%s' (The "
"'/' after server is mandatory)"
msgstr ""
"Wystąpił błąd podczas dopasowywania ciągu „%s” do wzoru „ssh://nazwa\\"
"_użytkownika:hasło@nazwa\\_serwera/zdalne\\_położenie” (znak „/” jest "
"wymagany po nazwie serwera)."

#: src/sbackup/fuse_plugins/sshFuseFAM.py:137
#, python-format
msgid ""
"The sshfs command '%(command)s' didn't perform normally. Output => "
"%(erroroutput)s "
msgstr ""
"Polecenie sshfs „%(command)s” nie zostało wykonane poprawnie. Wyjście: "
"%(erroroutput)s "

#: src/sbackup/fuse_plugins/sshFuseFAM.py:142
msgid "SSH schema is like : ssh://user:pass@example.com:33/home/user/backup/"
msgstr ""
"Wzór adresu SSH: ssh://nazwa\\_użytkownika:hasło@nazwa_komputera:33/zdalne\\"
"_położenie"

#: src/sbackup/fuse_plugins/sshFuseFAM.py:158
#, python-format
msgid ""
"Error matching the schema 'ssh://user:pass@example.com:21/home/' with '%s' "
"(The '/' after server is mandatory)"
msgstr ""
"Wystąpił błąd podczas dopasowywania ciągu „%s” do wzoru „ssh://nazwa\\"
"_użytkownika:hasło:21@nazwa\\_serwera/zdalne\\_położenie” (znak „/” jest "
"wymagany po nazwie serwera)."

#: src/sbackup/ui/GladeWindow.py:210
msgid ""
"Please make sure the missing directory exists (e.g. by mounting an external "
"disk) or change the specified target."
msgstr ""
"Proszę upewnić się, że nieodnaleziony katalog istnieje (np. montując nośnik "
"pamięci) lub zmienić położenie docelowe."

#: src/sbackup/ui/GladeWindow.py:211
#, python-format
msgid ""
"While accessing the backup destination following error occurred:\n"
"\n"
"%s."
msgstr ""
"Wystąpił błąd podczas próby dostępu do położenia docelowego kopii "
"zapasowej:\n"
"\n"
"%s."

#: src/sbackup/ui/GladeWindow.py:212 src/sbackup/ui/restoregui.py:797
msgid "Simple Backup error"
msgstr "Błąd narzędzia prostego tworzenia kopii zapasowej"

#: src/sbackup/ui/GladeWindow.py:213
msgid "Unable to access backup destination"
msgstr "Nie można uzyskać dostępu do położenia docelowego kopii zapasowej"

#: src/sbackup/ui/configgui.py:125
msgid "Scheduled backups are available for Administrator users only."
msgstr ""
"Harmonogram kopii zapasowych jest dostępny tylko dla użytkowników "
"posiadających uprawnienia administratorskie."

#: src/sbackup/ui/configgui.py:135 src/sbackup/ui/configgui.py:144
msgid "Name"
msgstr "Nazwa"

#: src/sbackup/ui/configgui.py:152
msgid "File Type"
msgstr "Typ pliku"

#: src/sbackup/ui/configgui.py:187
msgid "Enable"
msgstr "Włączenie"

#: src/sbackup/ui/configgui.py:188
msgid "Profile Name"
msgstr "Nazwa profilu"

#: src/sbackup/ui/configgui.py:285
#, python-format
msgid ""
"Invalid or empty regular expression ('%s') found in configuration. Removed."
msgstr ""
"Napotkano niepoprawne lub puste wyrażenie regularne „%s” w ustawieniach. "
"Usunięto."

#: src/sbackup/ui/configgui.py:292
#, python-format
msgid ""
"Invalid or empty regular expressions found\n"
"in configuration file:\n"
"'%s'\n"
"\n"
"These expressions are not used and were\n"
"removed from the configuration."
msgstr ""
"Napotkano na niepoprawne lub puste wyrażenie\n"
"regularne w pliku ustawień:\n"
"„%s”\n"
"\n"
"Wyrażenia te nie są używane i zostały\n"
"usunięte z ustawień."

#: src/sbackup/ui/configgui.py:548
msgid ""
"Please make sure the missing directory exists (e.g. by mounting an external "
"disk) or change the specified target to an existing one."
msgstr ""
"Proszę upewnić się, że brakujący katalog istnieje (np. montując określony "
"nośnik) lub zmienić wprowadzony katalog na taki, który istnieje."

#: src/sbackup/ui/configgui.py:549
#, python-format
msgid ""
"Backup target `%s` does not exist.\n"
"\n"
"Attention: The target will be set to the default value. Check this on the "
"destination settings page before saving the configuration."
msgstr ""
"Położenie docelowe „%s” nie istnieje.\n"
"\n"
"Uwaga: zostanie użyte domyślne położenie docelowe. Proszę sprawdzić "
"ustawienia przed zapisaniem konfiguracji."

#: src/sbackup/ui/configgui.py:551
msgid "Unable to open backup target"
msgstr "Nie można otworzyć położenia docelowego"

#: src/sbackup/ui/configgui.py:623
#, python-format
msgid ""
"%s\n"
"\n"
"A backup profile using default values was created. Save the new "
"configuration in order to use it or check your existing configuration file "
"manually.\n"
"\n"
"Important note: Saving will overwrite your existing invalid configuration."
msgstr ""

#: src/sbackup/ui/configgui.py:641
#, python-format
msgid "Current profile: %s"
msgstr "Bieżący profil: %s"

#: src/sbackup/ui/configgui.py:732
msgid "Already included item !"
msgstr "Element został już uwzględniony!"

#: src/sbackup/ui/configgui.py:747
msgid "Already excluded item !"
msgstr "Element został już wykluczony!"

#: src/sbackup/ui/configgui.py:759 src/sbackup/ui/configgui.py:1458
msgid "Empty expression. Please enter a valid regular expression."
msgstr ""
"Nie wprowadzono wyrażenia. Proszę wpisać prawidłowe wyrażenie regularne."

#: src/sbackup/ui/configgui.py:774 src/sbackup/ui/configgui.py:1472
msgid "Provided regular expression is not valid."
msgstr "Podane wyrażenie regularne nie jest poprawne."

#: src/sbackup/ui/configgui.py:782
msgid "Empty filename or path. Please enter a valid filename or path."
msgstr ""
"Pusta nazwa pliku lub ścieżka. Proszę wpisać prawidłową ścieżkę lub nazwę "
"pliku."

#: src/sbackup/ui/configgui.py:791
msgid ""
"It seems the path you entered does not exists. Do you want to add this "
"incorrect path?"
msgstr "Wprowadzona ścieżka nie istnieje. Dodać ją?"

#: src/sbackup/ui/configgui.py:820
msgid "Save configuration as..."
msgstr "Wybór pliku"

#: src/sbackup/ui/configgui.py:887
msgid ""
"A backup process is now executed in the background.\n"
"\n"
"You can monitor the progress of the backup by means of the status indicator "
"displayed in the notification area."
msgstr ""
"Proces wykonywania kopii zapasowej jest przeprowadzany w tle. Jego postęp "
"jest wyświetlany w obszarze powiadamiania."

#: src/sbackup/ui/configgui.py:888
msgid "Backup process started"
msgstr "Rozpoczęto tworzenie kopii zapasowej"

#: src/sbackup/ui/configgui.py:893 src/sbackup/ui/configgui.py:1661
#: src/sbackup/ui/configgui.py:2038
#, python-format
msgid "Unexpected dialog response: %s"
msgstr ""

#: src/sbackup/ui/configgui.py:967
msgid "Include file..."
msgstr "Wybór pliku"

#: src/sbackup/ui/configgui.py:974 src/sbackup/ui/configgui.py:1029
msgid "All files"
msgstr "Wszystkie pliki"

#: src/sbackup/ui/configgui.py:994
msgid "Include folder..."
msgstr "Wybór katalogu"

#: src/sbackup/ui/configgui.py:1022
msgid "Exclude file..."
msgstr "Wybór pliku"

#: src/sbackup/ui/configgui.py:1045
msgid "Exclude folder..."
msgstr "Wybór katalogu"

#: src/sbackup/ui/configgui.py:1310
msgid "Configuration has changed"
msgstr "Ustawienia zostały zmienione"

#: src/sbackup/ui/configgui.py:1311
msgid ""
"There are unsaved modifications. Please save the configuration or revert "
"these changes before testing the mail settings."
msgstr ""
"Zmiany ustawień nie zostały zapisane. Proszę zapisać ustawienia lub cofnąć "
"je przed rozpoczęciem testowania ustawień poczty elektronicznej."

#: src/sbackup/ui/configgui.py:1317 src/sbackup/ui/configgui.py:1323
msgid "Test mail settings"
msgstr "Testowanie ustawień poczty"

#: src/sbackup/ui/configgui.py:1318
msgid "The test failed with following output:"
msgstr "Test został zakończony z następującym błędem:"

#: src/sbackup/ui/configgui.py:1324
msgid "The test was successful."
msgstr "Test został zakończony pomyślnie."

#: src/sbackup/ui/configgui.py:1407 src/sbackup/ui/configgui.py:1450
#, python-format
msgid ""
"The given expression contains unsupported characters ('%s'). Currently it is "
"not possible to use these characters in exclude expressions."
msgstr ""
"Wprowadzone wyrażenie zawiera nieobsługiwane znaki („%s”). W tej chwili nie "
"ma możliwości użycia tych znaków określając wykluczone elementy ."

#: src/sbackup/ui/configgui.py:1410 src/sbackup/ui/configgui.py:1453
msgid "Unsupported character"
msgstr "Nieobsługiwany znak"

#: src/sbackup/ui/configgui.py:1621
msgid "Connect to remote destination"
msgstr ""

#: src/sbackup/ui/configgui.py:1669
msgid "Mount was sucessful (no errors)"
msgstr "Zamontowano (brak błędów)"

#: src/sbackup/ui/configgui.py:1680
msgid "Unable to mount host"
msgstr "Nie można zamontować zdalnego położenia"

#: src/sbackup/ui/configgui.py:1689
msgid "Umount was sucessful (no errors)"
msgstr "Odmontowano (brak błędów)"

#: src/sbackup/ui/configgui.py:1699
msgid "Unable to unmount host"
msgstr "Nie można odmontować zdalnego położenia"

#: src/sbackup/ui/configgui.py:1729
msgid "Perfom tests on remote host"
msgstr ""

#: src/sbackup/ui/configgui.py:1742
msgid "Unable to access remote destination"
msgstr "Nie można uzyskać dostępu do zdalnego położenia"

#: src/sbackup/ui/configgui.py:1746
msgid "All tests passed"
msgstr "Wszystkie testy zostały zakończone pomyślnie"

#: src/sbackup/ui/configgui.py:1910
msgid ""
"The given name of the new profile is empty. Please enter a valid profile "
"name."
msgstr ""
"Nazwa nowego profilu jest pusta. Proszę podać prawidłową nazwę profilu."

#: src/sbackup/ui/configgui.py:1911 src/sbackup/ui/configgui.py:1918
msgid "Profile name not valid"
msgstr "Niepoprawna nazwa profilu"

#: src/sbackup/ui/configgui.py:1917
msgid ""
"The given name of the new profile already exists. Please enter another name."
msgstr "Nazwa nowego profilu już istnieje. Proszę podać inną nazwę."

#: src/sbackup/ui/configgui.py:1919
msgid "Renaming of profiles is not supported."
msgstr "Zmiana nazw profili nie jest obsługiwana."

#: src/sbackup/ui/configgui.py:1949
#, python-format
msgid ""
"<b>Delete configuration profile?</b>\n"
"\n"
"You are trying to remove a configuration profile. You will not be able to "
"restore it. If you are not sure, use the 'enable|disable' functionality "
"instead.\n"
"\n"
"Do you really want to delete the profile '%(name)s'?"
msgstr ""
"<b>Usuwanie profilu ustawień</b>\n"
"\n"
"Nie ma możliwości przywrócenia usuniętego profilu. W celu wyłączenia profilu "
"należy odznaczyć pole wyboru „Włączenie” na liście profilów.\n"
"\n"
"Usunąć profil ustawień „%(name)s”?"

#: src/sbackup/ui/configgui.py:2022
#, python-format
msgid ""
"<big><b>Set default values for current profile?</b></big>\n"
"This will restore the default values for the profile currently edited: "
"'%s'.\n"
"\n"
"These predefined settings are recommended for most users. Check whether they "
"are appropriate for your use before saving the changed configuration."
msgstr ""
"<big><b>Przywracanie domyślnych wartości</b></big>\n"
"\n"
"Predefiniowane ustawienia są rekomendowane dla większości użytkowników. "
"Proszę sprawdzić czy będą one odpowiednie przed zapisaniem zmienionej "
"konfiguracji profilu.\n"
"\n"
"Przywrócić domyślne wartości dla profilu ustawień „%s”?"

#: src/sbackup/ui/configgui.py:2032
msgid "Default settings are being applied."
msgstr "Zastosowywanie domyślnych ustawień."

#: src/sbackup/ui/configgui.py:2057
msgid ""
"<b>Unable to remove default profile</b>\n"
"\n"
"The default profile cannot be removed. In the case you want to use just a "
"single profile, please set up the default profile accordingly."
msgstr ""
"<b>Usuwanie profilu ustawień</b>\n"
"\n"
"Nie można usunąć domyślnego profilu ustawień. W przypadku gdy zachodzi "
"potrzeba użycia tylko jednego profilu, należy skonfigurować jedynie profil "
"domyślny."

#: src/sbackup/ui/configgui.py:2071
msgid ""
"<b>Unable to remove default profile</b>\n"
"\n"
"The default profile cannot be disabled. In the case you want to use just a "
"single profile, please set up the default profile accordingly."
msgstr ""
"<b>Wyłączanie profilu ustawień</b>\n"
"\n"
"Nie można wyłączyć domyślnego profilu ustawień. W przypadku gdy zachodzi "
"potrzeba użycia tylko jednego profilu, należy skonfigurować jedynie profil "
"domyślny."

#: src/sbackup/ui/configgui.py:2085
msgid ""
"<b>No backup profile found.</b>\n"
"\n"
"No default profile was found. You are probably running Simple Backup for the "
"first time. A backup profile using default values was created.\n"
"\n"
"Please modify the settings according to your needs and save the "
"configuration in order to use it."
msgstr ""
"<b>Brak profilu ustawień</b>\n"
"\n"
"Prawdopodobnie program został uruchomiony pierwszy raz. Utworzono profil "
"ustawień kopii zapasowych używając wartości domyślnych.\n"
"\n"
"Proszę zmodyfikować ustawienia w zależności od potrzeb i zapisać je, aby móc "
"ich użyć."

#: src/sbackup/ui/configgui.py:2098
msgid "Please select a profile."
msgstr "Proszę wybrać profil."

#: src/sbackup/ui/indicator_core.py:117
msgid "there was a problem initializing the pynotify module"
msgstr "wystąpiły problemy podczas inicjacji modułu pynotify"

#: src/sbackup/ui/indicator_core.py:148 src/sbackup/ui/indicator_core.py:197
#: src/sbackup/ui/indicator_core.py:225 src/sbackup/ui/indicator_core.py:247
#, python-format
msgid "Connection to notification-daemon failed: %s"
msgstr "Nie udało się połączyć z demonem powiadamiania: %s"

#: src/sbackup/ui/indicator_core.py:310
msgid "Simple Backup"
msgstr "Proste tworzenie kopii zapasowej"

#: src/sbackup/ui/indicator_core.py:316
msgid "Show message windows"
msgstr ""

#: src/sbackup/ui/indicator_core.py:358 src/sbackup/ui/indicator_core.py:816
msgid "Cancel Backup"
msgstr "Anuluj"

#: src/sbackup/ui/indicator_core.py:420
msgid "Connection to D-Bus service lost."
msgstr "Połączenie z usługą D-Bus zostało przerwane."

#: src/sbackup/ui/indicator_core.py:445
msgid "re-connection was successful"
msgstr "Połączono ponownie"

#: src/sbackup/ui/indicator_core.py:484
msgid ""
"No backup in progress and connection to D-Bus service lost. Simple Backup "
"Indicator is being terminated."
msgstr ""

#: src/sbackup/ui/indicator_core.py:513
msgid "Starting backup session"
msgstr "Rozpoczynanie sesji kopii zapasowej"

#: src/sbackup/ui/indicator_core.py:527
msgid "Ending Backup Session"
msgstr "Kończenie sesji kopii zapasowej"

#: src/sbackup/ui/indicator_core.py:540
#, python-format
msgid "Unknown D-Bus event `%s` received."
msgstr "Odebrano nieznane zdarzenie usługi D-Bus „%s”."

#: src/sbackup/ui/indicator_core.py:581
msgid "Try again"
msgstr "Spróbuj ponownie"

#: src/sbackup/ui/indicator_core.py:651
msgid ""
"Attempt of starting another instance of Simple Backup while this one is "
"already running."
msgstr ""

#: src/sbackup/ui/indicator_core.py:661
#, python-format
msgid "Unable to present window: %s"
msgstr "Nie można wyświetlić okna: %s"

#: src/sbackup/ui/indicator_core.py:677
#, python-format
msgid "Do you really want to cancel the backup process of profile '%s'?"
msgstr "Anulować wykonywanie kopii zapasowej profilu „%s”?"

#: src/sbackup/ui/indicator_core.py:681
msgid "Cancel running backup process?"
msgstr "Anulować wykonywanie kopii zapasowej?"

#: src/sbackup/ui/indicator_core.py:698
msgid "Unable to cancel backup process."
msgstr "Nie można anulować wykonywania kopii zapasowej."

#: src/sbackup/ui/indicator_core.py:760
#, python-format
msgid "Profile: %s"
msgstr "Profil: %s"

#: src/sbackup/ui/indicator_core.py:761
#, python-format
msgid "Size of backup: %s"
msgstr "Rozmiar kopii: %s"

#: src/sbackup/ui/indicator_core.py:762
#, python-format
msgid "%.1f%% processed"
msgstr "Ukończono %.1f%%"

#: src/sbackup/ui/indicator_core.py:763
#, python-format
msgid "Remaining time: %s"
msgstr "Pozostały czas: %s"

#: src/sbackup/ui/indicator_core.py:809
#, python-format
msgid "PID of backup process being canceled: %s"
msgstr "Identyfikator procesu anulowanej kopii zapasowej: %s"

#: src/sbackup/ui/indicator_core.py:814
#, python-format
msgid "Unable to send signal to process %s"
msgstr "Nie można wysłać sygnału do procesu %s"

#: src/sbackup/ui/indicator_core.py:815
#, python-format
msgid "Sending signal using gksu to process %s"
msgstr "Wysyłanie sygnału do procesu %s, przy użyciu programu gksu"

#: src/sbackup/ui/indicator_core.py:819
#, python-format
msgid "Sending signal using gksu to process %s failed"
msgstr "Nie udało się wysłać sygnał do procesu %s, przy użyciu programu gksu"

#: src/sbackup/ui/indicator_core.py:854
#, python-format
msgid ""
"<b>Unable to find specified target directory</b>\n"
"\n"
"The specified target directory '%s' was not found.\n"
"\n"
msgstr ""
"<b>Nie odnaleziono położenia<b>\n"
"\n"
"Nie można odnaleźć położenia docelowego „%s”.\n"
"\n"

#: src/sbackup/ui/indicator_core.py:855
#, python-format
msgid ""
"You can try to use the specified target again or cancel the profile "
"execution. The specified destination is automatically used in %s seconds."
msgstr ""

#: src/sbackup/ui/indicator_core.py:882 src/sbackup/ui/indicator_core.py:924
#: src/sbackup/ui/indicator_core.py:942 src/sbackup/ui/indicator_core.py:950
#: src/sbackup/ui/indicator_core.py:967
msgid "unknown"
msgstr "nieznany"

#: src/sbackup/ui/indicator_core.py:903
msgid "less than 1 minute"
msgstr "mniej niż 1 minuta"

#: src/sbackup/ui/indicator_core.py:905
msgid "about 2 minutes"
msgstr "około 2 minuty"

#: src/sbackup/ui/indicator_core.py:907
msgid "about 3 minutes"
msgstr "około 3 minuty"

#: src/sbackup/ui/indicator_core.py:909
msgid "about 4 minutes"
msgstr "około 4 minut"

#: src/sbackup/ui/indicator_core.py:911
msgid "about 5 minutes"
msgstr "około 5 minut"

#: src/sbackup/ui/indicator_core.py:913
#, python-format
msgid "about %.0f minutes"
msgstr "około %.0f minut"

#: src/sbackup/ui/indicator_core.py:923
msgid "In progress"
msgstr "W trakcie"

#: src/sbackup/ui/indicator_core.py:933 src/sbackup/ui/indicator_core.py:959
msgid "finished"
msgstr "zakończono"

#: src/sbackup/ui/indicator_core.py:941
msgid "Progress: unknown"
msgstr "Postęp: nieznany"

#: src/sbackup/ui/indicator_core.py:948
msgid "Backup is being prepared"
msgstr "Przygotowywanie kopii zapasowej"

#: src/sbackup/ui/indicator_core.py:949
msgid "Collecting file info"
msgstr "Gromadzenie informacji o plikach"

#: src/sbackup/ui/indicator_core.py:958
msgid "Progress: canceled"
msgstr "Postęp: anulowano"

#: src/sbackup/ui/indicator_core.py:980
msgid "An error occurred"
msgstr "Wystąpił błąd"

#: src/sbackup/ui/indicator_core.py:1013
msgid "Another `Simple Backup Indicator` is already running."
msgstr ""

#: src/sbackup/ui/indicator_core.py:1037
#, python-format
msgid "Initialization of GTK+ failed: %s"
msgstr "Nie udało się zainicjować GTK+: %s"

#: src/sbackup/ui/misc.py:294
#, python-format
msgid "%s   (Administrator mode)"
msgstr ""

#: src/sbackup/ui/misc.py:324
#, python-format
msgid ""
"An uncaught error occurred. Close this message window and restart the "
"application.\n"
"\n"
"Please report this error on https://bugs.launchpad.net/sbackup.\n"
"\n"
"%s"
msgstr ""
"Wystąpił nieoczekiwany błąd. Proszę zamknąć to okno i uruchomić ponownie "
"program.\n"
"\n"
"Proszę zgłosić wiadomość o tym błędzie pod adresem "
"https://bugs.launchpad.net/sbackup.\n"
"\n"
"%s"

#: src/sbackup/ui/misc.py:325
msgid "Sorry, this should not have happened"
msgstr "Program uległ awarii. Przepraszamy."

#: src/sbackup/ui/restoregui.py:78
msgid "Restore..."
msgstr "Przywróć..."

#: src/sbackup/ui/restoregui.py:79 data/ui/sbackup-restore.glade:765
msgid "Restore as..."
msgstr "Przywróc jako..."

#: src/sbackup/ui/restoregui.py:80
msgid "Revert..."
msgstr "Przywróć rekurencynie..."

#: src/sbackup/ui/restoregui.py:81 data/ui/sbackup-restore.glade:797
msgid "Revert as..."
msgstr "Przywróć rekurencyjnie jako..."

#: src/sbackup/ui/restoregui.py:128 data/ui/sbackup-restore.glade:111
#: data/ui/sbackup-restore.glade:511
msgid "n.a."
msgstr "n/d"

#: src/sbackup/ui/restoregui.py:146 src/sbackup/ui/restoregui.py:163
msgid "Snapshots"
msgstr "Zrzuty danych"

#: src/sbackup/ui/restoregui.py:147
msgid "Version"
msgstr "Wersja"

#: src/sbackup/ui/restoregui.py:154 data/ui/sbackup-config.glade:4063
msgid "Path"
msgstr "Ścieżka"

#: src/sbackup/ui/restoregui.py:159
msgid "State"
msgstr "Stan"

#: src/sbackup/ui/restoregui.py:187
msgid "Connect to destination..."
msgstr ""

#: src/sbackup/ui/restoregui.py:211
msgid "Specified path does not exist"
msgstr "Wprowadzone położenie nie istnieje"

#: src/sbackup/ui/restoregui.py:257
msgid "Ready"
msgstr "Gotowy"

#: src/sbackup/ui/restoregui.py:371
msgid "No destination specified"
msgstr "Nie określono położenia docelowego"

#: src/sbackup/ui/restoregui.py:388
msgid "Choose a source folder"
msgstr "Wybierz folder źródłowy"

#: src/sbackup/ui/restoregui.py:405
msgid "Reading snapshots..."
msgstr "Odczytywanie zrzutu danych..."

#: src/sbackup/ui/restoregui.py:428
msgid "Reading directory content..."
msgstr "Odczytywanie zawartości katalogu..."

#: src/sbackup/ui/restoregui.py:458 src/sbackup/ui/restoregui.py:496
msgid "Loading ..."
msgstr "Wczytywanie..."

#: src/sbackup/ui/restoregui.py:539
msgid "Reading files from snapshot..."
msgstr "Odczytywanie plików zrzutu danych..."

#: src/sbackup/ui/restoregui.py:552
msgid "Simple Backup restore error"
msgstr ""

#: src/sbackup/ui/restoregui.py:553
msgid "An error occurred while reading snapshot"
msgstr "Wystąpił błąd podczas wczytywania zrzutu danych"

#: src/sbackup/ui/restoregui.py:557
msgid "This snapshot seems empty."
msgstr "Zrzut danych jest pusty."

#: src/sbackup/ui/restoregui.py:576
msgid "Reading backup snapshot..."
msgstr "Odczytywanie zrzutu danych kopii zapasowej..."

#: src/sbackup/ui/restoregui.py:599
msgid "No backups found for this day."
msgstr "Nie odnaleziono kopii zapasowych wykonanych we wskazanym dniu."

#: src/sbackup/ui/restoregui.py:614 src/sbackup/ui/restoregui.py:771
#, python-format
msgid ""
"Snapshot version is not supported (Only %(supportedversion)s is supported). "
"Version '%(currentversion)s' found."
msgstr ""

#: src/sbackup/ui/restoregui.py:643
msgid "Select restore location"
msgstr "Wybór położenia"

#: src/sbackup/ui/restoregui.py:662
#, python-format
msgid "Do you really want to revert '%s'?"
msgstr "Przywrócić rekurencyjnie „%s”?"

#: src/sbackup/ui/restoregui.py:676
msgid "Select revert location"
msgstr "Wybór położenia"

#: src/sbackup/ui/restoregui.py:685
#, python-format
msgid "Do you really want to revert '%(source)s' to '%(dir)s'?"
msgstr "Przywrócić rekurencyjnie „%(source)s” do położenia „%(dir)s”?"

#: src/sbackup/ui/restoregui.py:763
msgid "Reading snapshot..."
msgstr "Odczytywanie zrzutu danych..."

#: src/sbackup/ui/restoregui.py:782
#, python-format
msgid ""
"Deleting the selected snapshot `%s` will remove your backup for this "
"particular point in time. You cannot undo this operation.\n"
"\n"
"Are you sure that you want to remove the snapshot permanently?"
msgstr ""
"Usunięcie zaznaczonego zrzutu danych „%s” spowoduje nieodwracalne "
"wykasowanie kopii zapasowej wykonanej w określonym czasie.\n"
"\n"
"Usunąć zrzut danych?"

#: src/sbackup/ui/restoregui.py:786
msgid "Do you really want to remove snapshot?"
msgstr "Usuwanie zrzutu danych"

#: src/sbackup/ui/restoregui.py:795
#, python-format
msgid ""
"While attempting to delete snapshot the following error occurred:\n"
"%s"
msgstr ""
"Wystąpił błąd podczas próby usunięcia zrzutu danych:\n"
"%s"

#: src/sbackup/ui/restoregui.py:798
msgid "Unable to delete snapshot"
msgstr "Nie można usunąć zrzutu danych"

#: src/sbackup/ui/restoregui.py:804
#, python-format
msgid ""
"The selected snapshot '%s' is referenced by more recent snapshots as base "
"snapshot.\n"
"\n"
"Remove all of these child snapshots in order to delete this snapshot."
msgstr ""

#: src/sbackup/ui/restoregui.py:806
msgid "Unable to remove snapshot"
msgstr "Nie można usunąć zrzutu danych"

#: src/sbackup/ui/restoregui.py:814
msgid "Termination in progress"
msgstr "Kończenie działania"

#: src/sbackup/ui/restoregui.py:830 src/sbackup/ui/restoregui.py:836
#: src/sbackup/ui/restoregui.py:842 src/sbackup/ui/restoregui.py:848
#: data/ui/sbackup-restore.glade:959
msgid "Simple Backup restoration"
msgstr "Proste przywracanie kopii zapasowej"

#: src/sbackup/ui/restoregui.py:831 src/sbackup/ui/restoregui.py:837
msgid "<b>Restoring of selected files</b>"
msgstr "<b>Przywracanie wskazanych plików</b>"

#: src/sbackup/ui/restoregui.py:832
#, python-format
msgid "Restoring of <tt>'%s'</tt> is in progress."
msgstr "Przywracanie <tt>'%s'</tt> trwa."

#: src/sbackup/ui/restoregui.py:833
#, python-format
msgid "Restoring of <tt>'%s'</tt> was successful."
msgstr "Przywrócono <tt>„%s”</tt>."

#: src/sbackup/ui/restoregui.py:834
#, python-format
msgid ""
"Restoring of <tt>'%s'</tt> was not successful.\n"
"\n"
"Following error occurred:\n"
msgstr ""
"Nie udało się przywrócić <tt>„%s”</tt>.\n"
"\n"
"Wystąpił następujący błąd:\n"

#: src/sbackup/ui/restoregui.py:838
#, python-format
msgid ""
"Restoring of <tt>'%(source)s'</tt>\n"
"to <tt>'%(dirname)s'</tt> is in progress."
msgstr ""
"Przywracanie<tt>'%(source)s'</tt>\n"
"do <tt>'%(dirname)s'</tt> trwa."

#: src/sbackup/ui/restoregui.py:839
#, python-format
msgid ""
"Restoring of <tt>'%(source)s'</tt>\n"
"to <tt>'%(dirname)s'</tt> was successful."
msgstr ""
"Przywrócono <tt>„%(source)s”</tt>\n"
"do położenia <tt>„%(dirname)s”</tt>."

#: src/sbackup/ui/restoregui.py:840
#, python-format
msgid ""
"Restoring of <tt>'%(source)s'</tt>\n"
"to <tt>'%(dirname)s'</tt> was not successful.\n"
"\n"
"Following error occurred:\n"
msgstr ""
"Nie udało się przywrócić <tt>„%(source)s”</tt>\n"
"do położenia <tt>„%(dirname)s”</tt>.\n"
"\n"
"Wystąpił następujący błąd:\n"

#: src/sbackup/ui/restoregui.py:843 src/sbackup/ui/restoregui.py:849
msgid "<b>Reverting selected files</b>"
msgstr "<b>Przywracanie rekurencyjne wskazanych plików</b>"

#: src/sbackup/ui/restoregui.py:844
#, python-format
msgid "Reverting of <tt>'%s'</tt> is in progress.\n"
msgstr "Trwa przywracanie rekurencyjne <tt>„%s”</tt>.\n"

#: src/sbackup/ui/restoregui.py:845
#, python-format
msgid "Reverting of <tt>'%s'</tt> was successful."
msgstr "Przywrócono rekurencyjnie <tt>„%s”</tt>."

#: src/sbackup/ui/restoregui.py:846
#, python-format
msgid ""
"Reverting of <tt>'%s'</tt> was not successful.\n"
"\n"
"Following error occurred:\n"
msgstr ""
"Nie udało się przywrócić rekurencyjnie <tt>„%s”</tt>.\n"
"\n"
"Wystąpił następujący błąd:\n"

#: src/sbackup/ui/restoregui.py:850
#, python-format
msgid ""
"Reverting of <tt>'%(source)s'</tt>\n"
"to <tt>'%(dirname)s'</tt> is in progress."
msgstr ""
"Trwa przywracanie rekurencyjne <tt>„%(source)s”</tt>\n"
"do położenia <tt>„%(dirname)s”</tt>."

#: src/sbackup/ui/restoregui.py:851
#, python-format
msgid ""
"Reverting of <tt>'%(source)s'</tt>\n"
"to <tt>'%(dirname)s'</tt> was successful."
msgstr ""
"Przywrócono rekurencyjnie <tt>„%(source)s”</tt>\n"
"do położenia <tt>„%(dirname)s”</tt>."

#: src/sbackup/ui/restoregui.py:852
#, python-format
msgid ""
"Reverting of <tt>'%(source)s'</tt>\n"
"to <tt>'%(dirname)s'</tt> was not successful.\n"
"\n"
"Following error occurred:\n"
msgstr ""
"Nie udało się przywrócić rekurencyjnie <tt>„%(source)s”</tt>\n"
"do położenia <tt>„%(dirname)s”</tt>.\n"
"\n"
"Wystąpił następujący błąd:\n"

#: src/sbackup/util/__init__.py:439
#, python-format
msgid "%(mb)d MiB %(kb)d KiB"
msgstr "%(mb)d MiB %(kb)d KiB"

#: src/sbackup/util/__init__.py:442
#, python-format
msgid "%(mb)d MiB %(kb)d KiB %(bytes)d"
msgstr "%(mb)d MiB %(kb)d KiB %(bytes)d"

#: src/sbackup/util/__init__.py:447
#, python-format
msgid "%(mb)d MB %(kb)d kB"
msgstr "%(mb)d MB %(kb)d kB"

#: src/sbackup/util/__init__.py:450
#, python-format
msgid "%(mb)d MB %(kb)d kB %(bytes)d"
msgstr "%(mb)d MB %(kb)d kB %(bytes)d"

#: src/sbackup/util/filecollect.py:335
#, python-format
msgid "File '%(file)s' is not accessable with error '%(error)s'."
msgstr "Nie można uzyskać dostępu do pliku „%(file)s”: %(error)s."

#: src/sbackup/util/filecollect.py:351
#, python-format
msgid ""
"File '%(file)s' cannot be opened for read access. Operation timed out."
msgstr ""
"Brak uprawnień do odczytania pliku „%(file)s”. Przekroczono limit czasu "
"operacji."

#: src/sbackup/util/filecollect.py:355
#, python-format
msgid ""
"File '%(file)s' cannot be opened for read access with error '%(error)s'."
msgstr "Brak uprawnień do odczytania pliku „%(file)s”: %(error)s."

#: src/sbackup/util/filecollect.py:372
#, python-format
msgid "Symbolic link '%(path)s' -> '%(ln_target)s' is a circular symlink."
msgstr ""
"Dowiązanie symboliczne „%(path)s” do położenia „%(ln_target)s” jest "
"rekurencyjne."

#: src/sbackup/util/filecollect.py:388
#, python-format
msgid "File '%(file)s' is backup's target directory."
msgstr "Położenie „%(file)s” jest położeniem docelowym kopii zapasowej."

#: src/sbackup/util/filecollect.py:393
#, python-format
msgid "Path '%(file)s' defined in excludes list."
msgstr ""
"Ścieżka „%(file)s” została wprowadzona na listę wykluczonych położeń."

#: src/sbackup/util/filecollect.py:401
#, python-format
msgid "File '%(file)s' matches regular expression '%(regex)s'."
msgstr "Plik „%(file)s” pasuje do wyrażenia regularnego „%(regex)s”."

#: src/sbackup/util/filecollect.py:419
#, python-format
msgid ""
"File '%(file)s' exceeds maximum file size ( %(filesize)s > %(maxsize)s)."
msgstr ""
"Plik „%(file)s” przekroczył dopuszczalny rozmiar (%(filesize)s > "
"%(maxsize)s)."

#: src/sbackup/util/filecollect.py:497
#, python-format
msgid "Error while checking directory '%(dir)s': %(error)s."
msgstr "Wystąpił błąd podczas sprawdzania katalogu „%(dir)s”: %(error)s."

#: src/sbackup/util/filecollect.py:548
msgid "Empty regular expression found. Skipped."
msgstr "Napotkano puste wyrażenie regularne. Pomijanie."

#: src/sbackup/util/filecollect.py:554
#, python-format
msgid "Invalid regular expression ('%s') found. Skipped."
msgstr "Napotkano niepoprawne wyrażenie regularne („%s”). Pomijanie"

#: src/sbackup/util/filecollect.py:573
msgid "No directories to backup defined."
msgstr ""
"Nie zdefiniowano katalogów dla których ma zostać utworzona kopia zapasowa"

#: src/sbackup/util/lock.py:76
msgid "Another application instance is already running."
msgstr "Inne wystąpienie programu jest aktualnie uruchomione."

#: src/sbackup/util/lock.py:78
msgid "Invalid lock file found. Is being removed."
msgstr "Odnaleziono niepoprawny plik blokady. Usuwanie."

#: src/sbackup/util/lock.py:128 src/sbackup/util/lock.py:142
#, python-format
msgid "Unable to remove lock file: %s"
msgstr "Nie można usunąć pliku blokady: %s"

#: src/sbackup/util/lock.py:132 src/sbackup/util/lock.py:144
msgid "Unable to remove lock file: File not found."
msgstr "Nie można usunąć pliku blokady: nie odnaleziono pliku."

#: data/ui/sbackup-config.glade:11
msgid "Exclude file type"
msgstr "Wyłącz typ pliku"

#: data/ui/sbackup-config.glade:26
msgid "Standard file types:"
msgstr "Standardowe typy plików:"

#: data/ui/sbackup-config.glade:63
msgid "Custom defined file type with "
msgstr "Samodzielnie określony typ pliku o "

#: data/ui/sbackup-config.glade:93
msgid "file extension"
msgstr "rozszerzeniu"

#: data/ui/sbackup-config.glade:163
msgid "Exclude by regex"
msgstr "Wprowadzanie wyrażenia regularnego"

#: data/ui/sbackup-config.glade:180
msgid ""
"Enter a regular expression.\n"
"Files and directories matching this expression will be excluded from backup."
msgstr ""
"Proszę wprowadzić wyrażenie regularne.\n"
"Pliki i katalogi pasujące do niego, zostaną wykluczone podczas wykonywania "
"kopii zapasowej."

#: data/ui/sbackup-config.glade:257
msgid "Enter the remote target to include"
msgstr ""

#: data/ui/sbackup-config.glade:278
msgid "Choose a plugin to get the format"
msgstr ""

#: data/ui/sbackup-config.glade:295
msgid "Choose your plugin :"
msgstr "Proszę wybrać wtyczkę:"

#: data/ui/sbackup-config.glade:367
msgid "Check"
msgstr ""

#: data/ui/sbackup-config.glade:479
msgid ""
"<b>Save changed configuration?</b>\n"
"\n"
"The configuration has changed. If you want to use the modified "
"configuration, you have to save it.\n"
"\n"
"Do you want to save the configuration now?"
msgstr ""
"<b>Zapisywanie ustawień</b>\n"
"\n"
"Konfiguracja została zmieniona. W celu użycia nowych ustawień, należy je "
"zapisać.\n"
"\n"
"Zapisać ustawienia?"

#: data/ui/sbackup-config.glade:572
msgid "Configuration Profile Manager"
msgstr "Menedżer profili ustawień"

#: data/ui/sbackup-config.glade:594
msgid ""
"You can set up multiple configuration profiles which are processed when "
"performing a backup. Each profile has its own set of settings including "
"backup destination, backup format etc."
msgstr ""
"Można skonfigurować kilka profili, które będą przetwarzane podczas "
"wykonywania kopii zapasowej. Każdy profil posiada swój zestaw ustawień, "
"wliczając w to położenie docelowe, format kopii itp."

#: data/ui/sbackup-config.glade:613
msgid "<b>Configuration profiles</b>"
msgstr "<b>Profile ustawień</b>"

#: data/ui/sbackup-config.glade:785
msgid ""
"<b>Add new profile</b>\n"
"\n"
"Please enter the new profile name and set the according checkbox in order to "
"enable resp. disable it."
msgstr ""
"<b>Dodawanie nowego profilu</b>\n"
"\n"
"Proszę wprowadzić nazwę nowego profilu. Aby włączyć lub wyłączyć "
"przetwarzanie profilu, należy odpowiednio ustawić stan pola wyboru poniżej."

#: data/ui/sbackup-config.glade:810
msgid "Profile name"
msgstr "Nazwa profilu"

#: data/ui/sbackup-config.glade:836
msgid "Enabled"
msgstr "Włączenie"

#: data/ui/sbackup-config.glade:915 data/ui/sbackup-restore.glade:7
msgid "Simple Backup Suite"
msgstr "Proste narzędzie kopii zapasowych"

#: data/ui/sbackup-config.glade:932
msgid "_File"
msgstr "_Plik"

#: data/ui/sbackup-config.glade:971
msgid "Save as..."
msgstr "Zapisz jako..."

#: data/ui/sbackup-config.glade:1008
msgid "_Tools"
msgstr "_Narzędzia"

#: data/ui/sbackup-config.glade:1016 data/ui/sbackup-config.glade:1140
msgid "Set default settings..."
msgstr "Przywróć domyślne ustawienia..."

#: data/ui/sbackup-config.glade:1037
msgid "Profile Manager..."
msgstr "Menedżer profilów..."

#: data/ui/sbackup-config.glade:1058
msgid "Make backup now"
msgstr "Utwórz kopię zapasową"

#: data/ui/sbackup-config.glade:1079
msgid "_Help"
msgstr "Pomo_c"

#: data/ui/sbackup-config.glade:1087
msgid "_View all help topics"
msgstr "_Spis treści"

#: data/ui/sbackup-config.glade:1103
msgid "_About this program"
msgstr "_O programie"

#: data/ui/sbackup-config.glade:1154
msgid "Reload configuration"
msgstr "Wczytuje ponownie ustawienia"

#: data/ui/sbackup-config.glade:1168
msgid "Save configuration"
msgstr "Zapisuje ustawienia"

#: data/ui/sbackup-config.glade:1191
msgid "Make a backup now"
msgstr "Tworzy kopię zapasową"

#: data/ui/sbackup-config.glade:1214
msgid "Open the profile manager"
msgstr "Otwiera menedżer profilów ustawień"

#: data/ui/sbackup-config.glade:1215
msgid "Profiles"
msgstr "Profile"

#: data/ui/sbackup-config.glade:1253
msgid ""
"none\n"
"gzip\n"
"bzip2"
msgstr ""
"Brak\n"
"gzip\n"
"bzip2"

#: data/ui/sbackup-config.glade:1271
msgid ""
"Compression format\n"
"Default is set to uncompressed backups."
msgstr "Format kompresji:"

#: data/ui/sbackup-config.glade:1290 data/ui/sbackup-config.glade:1403
msgid ""
"You can split the snapshot to make backup on some filesystem that doesn't "
"support large files. This functionality can not be used if the backup is "
"compressed."
msgstr ""
"Dzieli zrzut danych w celu wykonania kopii zapasowej na systemach plików nie "
"obsługujących plików o dużych rozmiarach. Tej opcji nie można użyć dla "
"skompresowanych archiwów."

#: data/ui/sbackup-config.glade:1330
msgid "Do a full backup at least once every"
msgstr "Wykonywanie pełnej kopii co"

#: data/ui/sbackup-config.glade:1339
msgid ""
"Unless a set number of days has passed since the last full backup, "
"incremental backups will be done."
msgstr ""
"Wstrzymuje wykonanie kompletnej kopii zapasowej i wykonuje kopie przyrostowe "
"dopóki nie minie określony czas od wykonania ostatniej kompletnej kopii"

#: data/ui/sbackup-config.glade:1356 data/ui/sbackup-config.glade:3015
msgid "days"
msgstr "dni"

#: data/ui/sbackup-config.glade:1370
msgid " "
msgstr " "

#: data/ui/sbackup-config.glade:1380 data/ui/sbackup-config.glade:2323
msgid "MiB"
msgstr "MiB"

#: data/ui/sbackup-config.glade:1405
msgid "Split backup archives into several chunks"
msgstr "Dzielenie archiwum kopii zapasowej na fragmenty:"

#: data/ui/sbackup-config.glade:1438 data/ui/sbackup-config.glade:2627
#: data/ui/sbackup-config.glade:2863 data/ui/sbackup-config.glade:3111
#: data/ui/sbackup-config.glade:3856
msgid "Help"
msgstr "Pomoc"

#: data/ui/sbackup-config.glade:1442 data/ui/sbackup-config.glade:2632
msgid "Show help topic about configuration GUI."
msgstr ""

#: data/ui/sbackup-config.glade:1475
msgid "General"
msgstr "Ogólne"

#: data/ui/sbackup-config.glade:1495
msgid "<b>Included files and directories</b>"
msgstr "<b>Uwzględnione pliki i katalogi</b>"

#: data/ui/sbackup-config.glade:1570 data/ui/sbackup-config.glade:1818
#: data/ui/sbackup-config.glade:2023 data/ui/sbackup-config.glade:2181
msgid "Remove"
msgstr "Usuń"

#: data/ui/sbackup-config.glade:1620 data/ui/sbackup-config.glade:1868
msgid "Add File"
msgstr "Dodaj plik"

#: data/ui/sbackup-config.glade:1671 data/ui/sbackup-config.glade:1919
msgid "Add Directory"
msgstr "Dodaj katalog"

#: data/ui/sbackup-config.glade:1718
msgid "Include"
msgstr "Uwzględnione"

#: data/ui/sbackup-config.glade:1739
msgid "<b>Excluded files and directories</b>"
msgstr "<b>Wykluczone pliki i katalogi</b>"

#: data/ui/sbackup-config.glade:1952
msgid "Paths"
msgstr "Ścieżki"

#: data/ui/sbackup-config.glade:2074 data/ui/sbackup-config.glade:2232
msgid "Add"
msgstr "Dodaj"

#: data/ui/sbackup-config.glade:2109
msgid "File types"
msgstr "Typy plików"

#: data/ui/sbackup-config.glade:2267
msgid ""
"Regular\n"
"Expressions"
msgstr ""
"Wyrażenia\n"
"regularne"

#: data/ui/sbackup-config.glade:2288
msgid "Do not backup files bigger than"
msgstr "Wykluczanie plików o rozmiarze większym niż"

#: data/ui/sbackup-config.glade:2344
msgid "Follow symbolic links"
msgstr "Podążanie za dowiązaniami symbolicznymi"

#: data/ui/sbackup-config.glade:2373
msgid "Others"
msgstr "Inne"

#: data/ui/sbackup-config.glade:2400
msgid "Exclude"
msgstr "Wykluczone"

#: data/ui/sbackup-config.glade:2421
msgid "Use default backup directory"
msgstr "Domyślny katalog kopii zapasowych"

#: data/ui/sbackup-config.glade:2446
msgid "/var/backup"
msgstr "/var/backup"

#: data/ui/sbackup-config.glade:2472
msgid "Use custom local backup directory"
msgstr "Katalog lokalny"

#: data/ui/sbackup-config.glade:2500
msgid "Select the destination folder"
msgstr "Wybór katalogu"

#: data/ui/sbackup-config.glade:2526
msgid "Use a remote site"
msgstr "Katalog zdalny"

#: data/ui/sbackup-config.glade:2568
msgid "ssh://username:password@example.com/remote/dir/"
msgstr "ssh://nazwaużytkownika:hasło@przykladowy.pl/zdalny/katalog"

#: data/ui/sbackup-config.glade:2580
msgid "Connect..."
msgstr "Połącz..."

#: data/ui/sbackup-config.glade:2672
msgid ""
"<i>The selected destination is not writeable with current permissions. "
"Backups cannot be stored there.</i>"
msgstr ""
"<i>Brak uprawnień do zapisywania we wskazanym położeniu. Kopia zapasowa nie "
"może być w nim przechowywana.</i>"

#: data/ui/sbackup-config.glade:2704
msgid "Destination"
msgstr "Położenie docelowe"

#: data/ui/sbackup-config.glade:2725
msgid "_No scheduled backups"
msgstr "_Brak"

#: data/ui/sbackup-config.glade:2742
msgid "_Simple"
msgstr "_Prosty"

#: data/ui/sbackup-config.glade:2747
msgid ""
"This option will make a backup not at a precise time but when the computer "
"is up. "
msgstr ""
"Wykonuje kopie zapasowe nie o określonym czasie ale kiedy komputer jest "
"włączony. "

#: data/ui/sbackup-config.glade:2761
msgid "_Custom"
msgstr "_Własny"

#: data/ui/sbackup-config.glade:2781
msgid "Do backups"
msgstr "Wykonywanie kopii zapasowej"

#: data/ui/sbackup-config.glade:2798
msgid "Cron time definition"
msgstr "Definicja czasu programu Cron:"

#: data/ui/sbackup-config.glade:2834
msgid ""
"hourly\n"
"daily\n"
"weekly\n"
"monthly"
msgstr ""
"co godzinę\n"
"co dzień\n"
"co tydzień\n"
"co miesiąc"

#: data/ui/sbackup-config.glade:2867
msgid "Show help topic about scheduled backups."
msgstr ""

#: data/ui/sbackup-config.glade:2905
msgid ""
"<small>You can configure scheduled (i.e. automated) backups either simply by "
"choosing an interval or precisely by a custom cron definition. See \"man 5 "
"crontab\" for cron time definition format.</small>"
msgstr ""
"<small>Harmonogram kopii zapasowych można skonfigurować w sposób prosty - "
"wybierając okres ich automatycznego wykonywania lub precyzyjny - określając "
"reguły wykonywania przez program cron. Podręcznik programu cron (man 5 "
"crontab) zawiera szczegółowy opis formatowania reguł.</small>"

#: data/ui/sbackup-config.glade:2937
msgid "Schedule"
msgstr "Harmonogram"

#: data/ui/sbackup-config.glade:2955
msgid "Enable purging of old backups"
msgstr "Usuwanie przestarzałych kopii zapasowych"

#: data/ui/sbackup-config.glade:2983
msgid "Simple cut-off: Erase all backups older than"
msgstr "Proste - usuwa wszystkie kopie starsze niż"

#: data/ui/sbackup-config.glade:3039
msgid "Logarithmic"
msgstr "Logarytmicze"

#: data/ui/sbackup-config.glade:3065
msgid ""
"<small>Keep progressively less backups into the past:\n"
"Keep all backups from yesterday\n"
"Keep one backup per day from last week\n"
"Keep one backup per week from last month\n"
"Keep one backup per month from last year\n"
"Keep one backup per quarter from 2nd last year\n"
"Keep one backup per year further into past</small>"
msgstr ""
"<small>Przechowuje mniejszą ilość kopii starszych, tzn:\n"
"wszystkie kopie z poprzedniego dnia,\n"
"jedną kopię z każdego dnia ostatniego tygodnia,\n"
"jedną kopię z każdego tygodnia ostatniego miesiąca,\n"
"jedną kopię z każdego miesiąca ostatniego roku,\n"
"jedną kopię z każdego kwartału ostatnich dwóch lat,\n"
"jedną kopię z każdego roku w przypadku dłuższego okresu.</small>"

#: data/ui/sbackup-config.glade:3116
msgid "Show help topic about purging of backups."
msgstr ""

#: data/ui/sbackup-config.glade:3152
msgid ""
"<small>Note: Additionally all incomplete and irrecoverable backups will be "
"erased as long as there is a complete backup snapshot made later on.</small>"
msgstr ""
"<small>Uwaga: Dodatkowo wszystkie niekompletne i nie możliwe do przywrócenia "
"kopie zapasowe są kasowane tak długo, jak tylko istnieje pełna migawka kopii "
"zapsowej stworzona później.</small>"

#: data/ui/sbackup-config.glade:3184
msgid "Purging"
msgstr "Usuwanie"

#: data/ui/sbackup-config.glade:3186
msgid "Cleaning old backups"
msgstr "Usuwanie starych kopii zapasowych"

#: data/ui/sbackup-config.glade:3209
msgid "<b>Logging</b>"
msgstr "<b>Dziennik</b>"

#: data/ui/sbackup-config.glade:3234
msgid "Debug is just for debbuging purpose.Info is the recommended setting"
msgstr ""
"Wartość „Debug” jest przeznaczona do diagnozowania błędów. Rekomendowana "
"wartość to „Info”."

#: data/ui/sbackup-config.glade:3236
msgid "Log level"
msgstr "Poziom szczegółów:"

#: data/ui/sbackup-config.glade:3248
msgid "Debug is just for debbuging purpose. Info is the recommended setting."
msgstr ""
"Wartość „Debug” jest przeznaczona do diagnozowania błędów. Rekomendowana "
"wartość to „Info”."

#: data/ui/sbackup-config.glade:3274
msgid "Log file directory"
msgstr "Położenie pliku dziennika:"

#: data/ui/sbackup-config.glade:3320
msgid "<b>Report by mail</b>"
msgstr "<b>Poczta elektroniczna</b>"

#: data/ui/sbackup-config.glade:3350
msgid "From"
msgstr "Od"

#: data/ui/sbackup-config.glade:3361
msgid "SMTP server"
msgstr "Serwer SMTP"

#: data/ui/sbackup-config.glade:3375 data/ui/sbackup-config.glade:4053
msgid "Port"
msgstr "Port"

#: data/ui/sbackup-config.glade:3391
msgid "To"
msgstr "Do"

#: data/ui/sbackup-config.glade:3478
msgid "Use a username and password"
msgstr "Uwierzytelnianie przy pomocy nazwy użytkownika i hasła"

#: data/ui/sbackup-config.glade:3508 data/ui/sbackup-config.glade:4075
msgid "Username"
msgstr "Nazwa użytkownika:"

#: data/ui/sbackup-config.glade:3540 data/ui/sbackup-config.glade:4124
msgid "Password"
msgstr "Hasło:"

#: data/ui/sbackup-config.glade:3584
msgid "Use secure connection"
msgstr "Nawiązywanie bezpiecznego połączenia"

#: data/ui/sbackup-config.glade:3615
msgid "Choose a certificate file"
msgstr "Wybór pliku"

#: data/ui/sbackup-config.glade:3629
msgid "Key"
msgstr "Klucz"

#: data/ui/sbackup-config.glade:3645
msgid "Certificate"
msgstr "Certyfikat"

#: data/ui/sbackup-config.glade:3659
msgid "Choose a key file"
msgstr "Wybór pliku"

#: data/ui/sbackup-config.glade:3731
msgid "Test _mail settings"
msgstr "Przetestuj _ustawienia"

#: data/ui/sbackup-config.glade:3772
msgid "Report"
msgstr "Raportowanie"

#: data/ui/sbackup-config.glade:3811
msgid "Warning"
msgstr "Ostrzeżenie"

#: data/ui/sbackup-config.glade:3860
msgid "Show help topic about default values."
msgstr ""

#: data/ui/sbackup-config.glade:3893
msgid "_Set"
msgstr "_Przywróć"

#: data/ui/sbackup-config.glade:3935
msgid "Set remote target"
msgstr "Określanie zdalnego położenia"

#: data/ui/sbackup-config.glade:3957
msgid "Type of service"
msgstr "Typ usługi:"

#: data/ui/sbackup-config.glade:3997
msgid "Hostname"
msgstr "Nazwa komputera:"

#: data/ui/sbackup-config.glade:4027
msgid "<b>Details</b>"
msgstr "<b>Szczegóły</b>"

#: data/ui/sbackup-config.glade:4157
msgid "Show password"
msgstr "Wyświetlanie hasła"

#: data/ui/sbackup-config.glade:4217
msgid "_Connect"
msgstr "_Połącz"

#: data/ui/sbackup-config.glade:4293
msgid "Make a full backup"
msgstr "Wykonanie kompletnej kopii"

#: data/ui/sbackup-legacy-restore.glade:7
msgid "Restore files/directories"
msgstr "Przywróc pliki lub katalogi"

#: data/ui/sbackup-legacy-restore.glade:25
msgid "<b>Restore Source Folder</b>"
msgstr "<b>Folder źródłowy przywracania</b>"

#: data/ui/sbackup-legacy-restore.glade:90
msgid "Available backups:"
msgstr "Dostępne kopie zapasowe:"

#: data/ui/sbackup-legacy-restore.glade:109
msgid ""
"Type in this box text like that:\n"
"\n"
"/home/user/folder - To use a local folder\n"
"ssh://user:password@machine:/remote/folder - To use a ssh location\n"
"ftp://user:password@machine:/remote/folder - To use a ftp location"
msgstr ""

#: data/ui/sbackup-legacy-restore.glade:179
msgid "Use custom:"
msgstr "Użyj własnego:"

#: data/ui/sbackup-legacy-restore.glade:200
msgid "Use default:"
msgstr "Użyj domyślnego:"

#: data/ui/sbackup-legacy-restore.glade:241
msgid "<b>Files and Folders to restore</b>"
msgstr "<b>Pliki i foldery do przywrócenia</b>"

#: data/ui/sbackup-legacy-restore.glade:345 data/ui/sbackup-restore.glade:782
msgid "Restore"
msgstr "Przywróć"

#: data/ui/sbackup-legacy-restore.glade:390
msgid "Restore As..."
msgstr "Przywróć jako..."

#: data/ui/sbackup-legacy-restore.glade:448
msgid "Restoring, this might take some time ..."
msgstr ""

#: data/ui/sbackup-legacy-restore.glade:463
msgid "gtk-cancel"
msgstr ""

#: data/ui/sbackup-restore.glade:38
msgid "<b>Backup destination</b>"
msgstr "<b>Położenie docelowe</b>"

#: data/ui/sbackup-restore.glade:52
msgid "Displays the manual in Help browser."
msgstr "Wyświetla podręcznik pomocy w przeglądarce dokumentacji"

#: data/ui/sbackup-restore.glade:85
msgid "Default profile's destination"
msgstr "Profilu domyślnego"

#: data/ui/sbackup-restore.glade:90
msgid ""
"Set backup destination to the place specified in default configuration "
"profile"
msgstr "Ustawia położenie kopii zapasowej określone w domyślnym profilu"

#: data/ui/sbackup-restore.glade:137
msgid "Custom destination"
msgstr "Własne"

#: data/ui/sbackup-restore.glade:143
msgid ""
"Select a backup destination on your harddisk or at a remote site. Press "
"Apply when ready."
msgstr ""
"Wprowadza własne lokalne lub zdalne położenie kopii zapasowej. Proszę "
"kliknąć przycisk „Zastosuj” w celu zmiany położenia."

#: data/ui/sbackup-restore.glade:184
msgid "Choose a destination folder. For remote sites fill URI in text field"
msgstr ""
"Wybiera katalog docelowy kopii zapasowej. W przypadku położeń zdalnych "
"proszę wprowadzić adres URI w polu tekstowym."

#: data/ui/sbackup-restore.glade:201
msgid "Change destination to path specified in left text field"
msgstr "Zmienia położenie kopii zapasowej na tą wprowadzoną w polu po lewej"

#: data/ui/sbackup-restore.glade:266
msgid "Select a bold printed date to get the list of backups for that date."
msgstr ""
"Proszę wybrać datę wypisaną pogrubioną czcionką, aby wyświetlić listę kopii "
"zapasowych wykonanych w tym dniu."

#: data/ui/sbackup-restore.glade:310
msgid "Available backups"
msgstr "Dostępne kopie zapasowe"

#: data/ui/sbackup-restore.glade:398
msgid "Delete snapshot"
msgstr "Usunięcie zrzutu danych"

#: data/ui/sbackup-restore.glade:436
msgid "Delete"
msgstr "Usuń"

#: data/ui/sbackup-restore.glade:473
msgid "<b>Snapshot History</b>"
msgstr "<b>Historia zrzutów danych</b>"

#: data/ui/sbackup-restore.glade:499
msgid "Current base:"
msgstr "Bieżąca baza:"

#: data/ui/sbackup-restore.glade:540
msgid "Select a snapshot on this list to rebase on it."
msgstr ""

#: data/ui/sbackup-restore.glade:615
msgid "Rebase"
msgstr ""

#: data/ui/sbackup-restore.glade:666
msgid "<b>Snapshot Management</b>"
msgstr "<b>Zarządzanie</b>"

#: data/ui/sbackup-restore.glade:705
msgid "Snapshot details"
msgstr "Szczegóły zrzutu danych"

#: data/ui/sbackup-restore.glade:770 data/ui/sbackup-restore.glade:787
msgid "Restores files/directories from the selected snapshot"
msgstr "Przywraca pliki i katalogi ze wskazanego zrzutu danych"

#: data/ui/sbackup-restore.glade:802 data/ui/sbackup-restore.glade:821
msgid ""
"Restores files/directories recursively starting from the base snapshot to "
"the selected snapshot"
msgstr ""
"Przywraca pliki i katalogi rekurencyjnie rozpoczynając od bazowego zrzutu "
"danych a kończąc na wskazanym zrzucie danych"

#: data/ui/sbackup-restore.glade:816
msgid "Revert"
msgstr "Przywróć rekurencyjnie"

#: data/ui/sbackup-restore.glade:859
msgid "<b>Restoration Management</b>"
msgstr "<b>Przywracanie</b>"

#: data/ui/sbackup-restore.glade:884
msgid "<b>Export Management</b>"
msgstr "<b>Eksportowanie</b>"

#: data/ui/sbackup-restore.glade:976
msgid "Headline"
msgstr "Nagłówek"

#: data/ui/sbackup-restore.glade:989
msgid "Content"
msgstr "Zawartość"

#, python-format
#~ msgid "Unable to remove upgrade stamp: %s"
#~ msgstr "Nie można usunąć oznaczenia aktualizacji: %s"

#, python-format
#~ msgid "Upgrading from v1.0 to v1.2: %s"
#~ msgstr "Aktualizowanie z wersji 1.0 do wersji 1.2: %s"

#, python-format
#~ msgid "Upgrading to v1.3: %s"
#~ msgstr "Aktualizowanie do wersji 1.3: %s"

#, python-format
#~ msgid "Upgrading to v1.4: %s"
#~ msgstr "Aktualizowanie do wersji 1.4: %s"

#, python-format
#~ msgid "Upgrading to v1.5: %s"
#~ msgstr "Aktualizowanie do wersji 1.5: %s"

#, python-format
#~ msgid "The SNAR file already exist for snapshot '%s'. It is not overwritten."
#~ msgstr "Plik SNAR zrzutu danych „%s” już istnieje. Nie zostanie zastąpiony."

#~ msgid ""
#~ "There are snapshots stored in outdated snapshot formats. Please upgrade them "
#~ "using 'Simple Backup-Restoration' if you want to use them."
#~ msgstr ""
#~ "Napotkano zrzuty danych przechowywane w nieaktualnych formatach. Proszę "
#~ "zaktualizować je używając „Prostego przywracania kopii zapasowych”, aby móc "
#~ "ich użyć."

#~ msgid "Unable to upgrade snapshot"
#~ msgstr "Nie można zaktualizować zrzutu danych"

#~ msgid "Do you really want to upgrade snapshot?"
#~ msgstr "Zaktualizować zrzut danych?"

#~ msgid "Snapshot was sucessfully upgraded."
#~ msgstr "Zaktualizowano zrzut danych."

#, python-format
#~ msgid "File '%(file)s' does not exist."
#~ msgstr "Plik „%(file)s” nie istnieje."

#~ msgid "Upgrade snapshot"
#~ msgstr "Zaktualizowanie zrzutu danych"

#~ msgid "Upgrade"
#~ msgstr "Zaktualizuj"

#, python-format
#~ msgid ""
#~ "Snapshot version is not supported (Only %(supportedversion)s is supported). "
#~ "Version '%(currentversion)s' found. You should upgrade it. "
#~ msgstr ""
#~ "Wersja zrzutu danych nie jest obsługiwana (wersja obsługiwana: "
#~ "%(supportedversion)s). Wersja zrzutu danych: %(currentversion)s. Proszę "
#~ "zaktualizować zrzut danych. "

#~ msgid "Upgrade finished"
#~ msgstr "Zakończono aktualizowanie"

#, python-format
#~ msgid ""
#~ "'%(snapshotToRebase)s'  doesn't have 'base' file , it might have been broken "
#~ msgstr ""
#~ "Zrzut danych „%(snapshotToRebase)s” nie posiada pliku bazowego lub został on "
#~ "uszkodzony. "

#, python-format
#~ msgid ""
#~ "Cannot rebase a snapshot on an earlier one : '%(snapshotToRebase)s' <= "
#~ "'%(NewBaseSnapshot)s' "
#~ msgstr ""
#~ "Nie można zmienić bazy zrzutu danych na wcześniejszą: „%(snapshotToRebase)s” "
#~ "<= „%(NewBaseSnapshot)s”. "

#, python-format
#~ msgid "Base of snapshot '%s' is not set."
#~ msgstr "Nie ustawiono bazy zrzutu danych „%s”."

#, python-format
#~ msgid ""
#~ "While attempting to upgrade snapshot the following error occurred:\n"
#~ "%s"
#~ msgstr ""
#~ "Wystąpił następujący błąd podczas próby zaktualizowania zrzutu danych:\n"
#~ "%s"

#, python-format
#~ msgid "No need to rebase a full snapshot '%s'"
#~ msgstr "Nie ma potrzeby zmieniać bazę kompletnego zrzutu danych „%s”"

#, python-format
#~ msgid "Rebasing '%(current)s' on '%(base)s'"
#~ msgstr "Zmienianie bazy z „%(current)s” na „%(base)s”"
